# Generated by Django 3.0.7 on 2020-06-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_partners', '0004_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
